version: "2.4"

services:
  team-assets:
    image: demo-team-assets
    build:
      context: team-assets
    ports:
      - "6100:80"
  team-shop-page:
    image: demo-team-shop-page
    build:
      context: team-shop-page
    ports:
      - "6500:80"
